services:
  oracle:
    image: inventage-base.artifacts.inventage.com/inventage/base/oracle/database:19c
    environment:
      # schema==user==passwort
      SCHEMAS: USERSTORAGE
    networks:
      - oracle
    ports:
      - "1521:1521"

networks:
  oracle: